// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnmmtawxyuionwhbfnbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubW10YXd4eXVpb253aGJmbmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDIzNjksImV4cCI6MjA2NjQxODM2OX0.6J7tUHCT416_-cEKmBOQN6ifin7SMwSFFciO8wIYaow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);